### ISSUE TITLE
Error: Layer weight shape (3, 3, 256, 64) not compatible with provided weight shape (64, 3, 3, 3)

### ISSUE THREAD

**Issue by marooncn** [qiaoguan/keras_dataAugmentation#4]
你好，我在运行代码
`python classifier_using_pretrained.py `
时出现如题报错，其中用到的数据集是自己的数据集，尺寸为256，已经在代码中修改。
另外，能附下实现的各个依赖库的版本吗？如Keras, keras后端

**Comment by qiaoguan** [comment]
可能keras版本的问题，keras确实不同版本还多接口都不一样，这个确实有点坑，我之前用的版本好像是2.08或者更前面的版本，我也记不太清了，时间过得有点久了。

**Comment by marooncn** [comment]
已经实现，支持最新版Keras，可查看[基于小样本的图片分类器](https://github.com/marooncn/Defect-Detection-Classifier)
